    version: '3.8'
    services:
      holmes_web:
        build:
          context: .
        ports:
          - "8000:8000"
        volumes:
          - .:/holmes_web
        environment:
          - DJANGO_SETTINGS_MODULE=holmes_web.settings

